#!/usr/bin/env bash

# Canonical original-CARD switches. Assign every value deliberately so an
# inherited finetune/SGC-CARD environment cannot alter a baseline run.
MODEL_TYPE=card
FEATURE_ROOT="${BASELINE_FEATURE_ROOT:-}"
USE_CHANGE_MASK=0
MASK_TYPE=binary
NUM_MASK_CLASSES=""
USE_SEMANTIC_MAPS=0
SEMANTIC_INPUT_MODE=none
NUM_SEMANTIC_CLASSES=""
ENABLE_AUX_MASK=0
USE_AUX_SEMANTIC=0
USE_SEMANTIC_PARTIAL_DETACH=0
USE_AUX_WARMUP=0
AUX_WARMUP_START_RATIO=0.0
AUX_WARMUP_END_RATIO=0.0
USE_FEATURE_REWEIGHT=0
DETACH_REWEIGHT_MASK=0
REWEIGHT_ALPHA=0.0
ALLOW_MISSING_PSEUDO_MASK=0
LMASK=0.0
LSEM=0.0
SEMANTIC_DETACH_RATIO=0.0
SEMANTIC_FUSION_GAMMA_INIT=0.0
SEMANTIC_FUSION_GAMMA_MAX=0.0
USE_CONTENT_WORD_WEIGHT=0
CONTENT_WORD_WEIGHT=1.0
NORMALIZE_CONTENT_WORD_WEIGHTS=0
MASK_LOSS_TYPE=""
SEMANTIC_LOSS_TYPE=""

# Canonical YAML owns schedule/optimizer/init. Empty exported values erase
# inherited grid/finetune overrides and make _run_paper_training omit them.
MAX_ITER=""
SNAPSHOT_INTERVAL=""
FINETUNE_STEPS=""
FINETUNE_DECODER_ONLY=0
SAVE_INTERVAL=""
EVAL_INTERVAL=""
LOG_INTERVAL=""
BATCH_SIZE=""
LR=""
INIT_CHECKPOINT=""
PAPER_SELECTION_MODE=0
SELECTION_STRATEGY=best_cider
SEED=1111

export MODEL_TYPE FEATURE_ROOT
export USE_CHANGE_MASK MASK_TYPE NUM_MASK_CLASSES USE_SEMANTIC_MAPS SEMANTIC_INPUT_MODE NUM_SEMANTIC_CLASSES
export ENABLE_AUX_MASK USE_AUX_SEMANTIC USE_SEMANTIC_PARTIAL_DETACH USE_AUX_WARMUP
export AUX_WARMUP_START_RATIO AUX_WARMUP_END_RATIO
export USE_FEATURE_REWEIGHT DETACH_REWEIGHT_MASK REWEIGHT_ALPHA ALLOW_MISSING_PSEUDO_MASK
export LMASK LSEM SEMANTIC_DETACH_RATIO SEMANTIC_FUSION_GAMMA_INIT SEMANTIC_FUSION_GAMMA_MAX
export USE_CONTENT_WORD_WEIGHT CONTENT_WORD_WEIGHT NORMALIZE_CONTENT_WORD_WEIGHTS MASK_LOSS_TYPE SEMANTIC_LOSS_TYPE
export MAX_ITER SNAPSHOT_INTERVAL FINETUNE_STEPS FINETUNE_DECODER_ONLY SAVE_INTERVAL EVAL_INTERVAL LOG_INTERVAL BATCH_SIZE LR INIT_CHECKPOINT
export PAPER_SELECTION_MODE SELECTION_STRATEGY SEED
