#!/usr/bin/env bash
set -euo pipefail
EXP_NAME="${EXP_NAME:-second_cc_card_rgb_baseline}"
DATASET="second_cc"
DATA_ROOT="${DATA_ROOT:-${SECOND_CC_ROOT:-./SECOND-CC-AUG}}"
BASE_CFG="${BASE_CFG:-configs/dynamic/transformer_second_cc_aug_baseline.yaml}"
MODEL_TYPE="card"
USE_CHANGE_MASK=0
MASK_TYPE="binary"
ENABLE_AUX_MASK=0
USE_AUX_SEMANTIC=0
USE_SEMANTIC_MAPS=0
SEMANTIC_INPUT_MODE="none"
USE_SEMANTIC_PARTIAL_DETACH=0
USE_FEATURE_REWEIGHT=0
LMASK=0
LSEM=0
export EXP_NAME DATASET DATA_ROOT BASE_CFG MODEL_TYPE USE_CHANGE_MASK MASK_TYPE ENABLE_AUX_MASK USE_AUX_SEMANTIC USE_SEMANTIC_MAPS SEMANTIC_INPUT_MODE USE_SEMANTIC_PARTIAL_DETACH USE_FEATURE_REWEIGHT LMASK LSEM
bash scripts/_run_paper_training.sh
