#!/usr/bin/env bash
set -euo pipefail
EXP_NAME="${EXP_NAME:-levir_mci_wcsg_card_final}"
DATASET="levir_mci"
DATA_ROOT="${DATA_ROOT:-${LEVIR_MCI_ROOT:-./LEVIR-MCI-dataset}}"
BASE_CFG="${BASE_CFG:-configs/levir_mci/wcsg_card_final.yaml}"
MODEL_TYPE="sgc_card"
USE_CHANGE_MASK=1
MASK_TYPE="multiclass"
NUM_MASK_CLASSES=3
ENABLE_AUX_MASK=1
USE_AUX_SEMANTIC=1
USE_SEMANTIC_MAPS=0
SEMANTIC_INPUT_MODE="aux"
USE_SEMANTIC_PARTIAL_DETACH=1
SEMANTIC_DETACH_RATIO="${SEMANTIC_DETACH_RATIO:-0.5}"
USE_FEATURE_REWEIGHT=0
LMASK="${LMASK:-0.003}"
LSEM="${LSEM:-0.005}"
MASK_LOSS_TYPE="ce_dice"
SEMANTIC_LOSS_TYPE="multilabel_bce"
export EXP_NAME DATASET DATA_ROOT BASE_CFG MODEL_TYPE USE_CHANGE_MASK MASK_TYPE NUM_MASK_CLASSES ENABLE_AUX_MASK USE_AUX_SEMANTIC USE_SEMANTIC_MAPS SEMANTIC_INPUT_MODE USE_SEMANTIC_PARTIAL_DETACH SEMANTIC_DETACH_RATIO USE_FEATURE_REWEIGHT LMASK LSEM MASK_LOSS_TYPE SEMANTIC_LOSS_TYPE
bash scripts/_run_paper_training.sh