#!/usr/bin/env bash
set -euo pipefail
EXP_NAME="${EXP_NAME:-second_cc_card_semantic_aux}"
DATASET="${DATASET:-second_cc}"
DATA_ROOT="${DATA_ROOT:-${SECOND_CC_ROOT:-./SECOND-CC-AUG}}"
BASE_CFG="${BASE_CFG:-configs/dynamic/transformer_second_cc_aug_sgc_card.yaml}"
MODEL_TYPE="${MODEL_TYPE:-sgc_card}"
USE_CHANGE_MASK="${USE_CHANGE_MASK:-0}"
ENABLE_AUX_MASK="${ENABLE_AUX_MASK:-0}"
USE_AUX_SEMANTIC="${USE_AUX_SEMANTIC:-1}"
USE_SEMANTIC_MAPS="${USE_SEMANTIC_MAPS:-1}"
SEMANTIC_INPUT_MODE="${SEMANTIC_INPUT_MODE:-aux}"
USE_SEMANTIC_PARTIAL_DETACH="${USE_SEMANTIC_PARTIAL_DETACH:-0}"
USE_FEATURE_REWEIGHT="${USE_FEATURE_REWEIGHT:-0}"
LMASK=0
LSEM="${LSEM:-0.005}"
SEMANTIC_LOSS_TYPE="${SEMANTIC_LOSS_TYPE:-ce_dice}"
export EXP_NAME DATASET DATA_ROOT BASE_CFG MODEL_TYPE USE_CHANGE_MASK ENABLE_AUX_MASK USE_AUX_SEMANTIC USE_SEMANTIC_MAPS SEMANTIC_INPUT_MODE USE_SEMANTIC_PARTIAL_DETACH USE_FEATURE_REWEIGHT LMASK LSEM SEMANTIC_LOSS_TYPE
bash scripts/_run_paper_training.sh
