#!/usr/bin/env bash
set -euo pipefail
EXP_NAME="${EXP_NAME:-levir_mci_card_semantic_loss}"
DATASET="levir_mci"
DATA_ROOT="${DATA_ROOT:-${LEVIR_MCI_ROOT:-./LEVIR-MCI-dataset}}"
BASE_CFG="${BASE_CFG:-configs/dynamic/transformer_levir_mci_sgc_card.yaml}"
MODEL_TYPE="sgc_card"
USE_CHANGE_MASK=0
MASK_TYPE="binary"
ENABLE_AUX_MASK=0
USE_AUX_SEMANTIC=1
USE_SEMANTIC_MAPS=0
SEMANTIC_INPUT_MODE="aux"
USE_SEMANTIC_PARTIAL_DETACH=0
USE_FEATURE_REWEIGHT=0
LMASK=0.0
LSEM="${LSEM:-0.005}"
SEMANTIC_LOSS_TYPE="multilabel_bce"
export EXP_NAME DATASET DATA_ROOT BASE_CFG MODEL_TYPE USE_CHANGE_MASK MASK_TYPE ENABLE_AUX_MASK USE_AUX_SEMANTIC USE_SEMANTIC_MAPS SEMANTIC_INPUT_MODE USE_SEMANTIC_PARTIAL_DETACH USE_FEATURE_REWEIGHT LMASK LSEM SEMANTIC_LOSS_TYPE
bash scripts/_run_paper_training.sh
