exp_name: 'sgc_card_levir_mci'
gpu_id: [0]
logger:
    display_id: 9908
model:
    enable_aux_mask: True
    semantic_input_mode: none
    transformer_encoder:
        input_dim: 2048
        feat_dim: 1024
        emb_dim: 512
        att_dim: 512
        att_head: 8
        att_layer: 2
        dim: 128
    transformer_decoder:
        input_dim: 2048
        word_dim: 300
        att_dim: 512
        att_head: 8
        att_layer: 2
        vocab_size: 860
        seq_length: 41
        share_wd_cls_weight: False
        label_smoothing: 0.0

data:
    dataset: 'levir_mci'
    default_feature_dir: "./LEVIR-MCI-dataset/features"
    semantic_feature_dir: "./LEVIR-MCI-dataset/features"
    default_img_dir: "./LEVIR-MCI-dataset/images"
    semantic_img_dir: "./LEVIR-MCI-dataset/images"
    default_phase: "A"
    semantic_phase: "B"
    pseudo_mask_root: "./LEVIR-MCI-dataset/images"
    pseudo_mask_phase: "label"
    allow_missing_pseudo_mask: False
    eval_anno_path: "./LEVIR-MCI-dataset/levir_mci_captions_reformat.json"
    splits_json: "./LEVIR-MCI-dataset/splits.json"
    vocab_json: "./LEVIR-MCI-dataset/transformer_levir_mci_vocab.json"
    h5_label_file: "./LEVIR-MCI-dataset/transformer_levir_mci_labels.h5"
    train:
        batch_size: 32
train:
    max_iter: 10000
    seed: 1111
    snapshot_interval: 1000
    grad_clip: -1.0
    lambda_mask: 0.003
    use_mask_conf_filter: True
    mask_conf_threshold: 0.5
    mask_ignore_index: -1
    use_mask_warmup: False
    mask_warmup_steps: 0
    mask_loss_type: "bce_dice"
    mask_bce_dice_alpha: 0.5
    use_feature_reweight: False
    reweight_alpha: 0.2
    use_semantic_aux: True
    lambda_semantic: 0.005
    use_semantic_warmup: False
    use_aux_warmup: True
    aux_warmup_start_ratio: 0.30
    aux_warmup_end_ratio: 0.70
    semantic_decay_start_ratio: 0.70
    semantic_decay_final_ratio: 0.50
    semantic_loss_type: "multilabel_bce"
    semantic_tag_file: "configs/semantic_tags/levir_cc_object_action_tags.txt"
    semantic_aux_dropout: 0.1
    semantic_normalize_synonyms: True
    use_semantic_detach: False
    use_semantic_partial_detach: True
    semantic_detach_ratio: 0.5
    semantic_update_visual: True
    use_relation_aux: False
    use_content_word_weight: False
    use_content_word_weighted_ce: False
    optim:
        type: 'adam'
        lr: 0.0002
        weight_decay: 0.0
        step_size: 17
        gamma: 0.1